leftnav:
- identifier: 551ce7b0-10f3-4e19-b6e8-7187c6985f8b
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: a85be76d-baf6-4737-ba1c-b7cb3fb12697
  name: Instructor Insights
  pageRef: /pages/instructor-insights
  weight: 20
- identifier: 689cf52a-0586-489e-ac3e-d528a3554eb8
  name: Calendar
  pageRef: /pages/calendar
  weight: 30
- identifier: b51259f6-3e24-43ba-b2b4-bc746e4cf49a
  name: Readings
  pageRef: /pages/readings
  weight: 40
- identifier: c5ae9d53-45ba-4be7-a516-847ac24c4b45
  name: Materials by Lecture
  pageRef: /pages/material-by-lecture
  weight: 50
- identifier: ad94fe13-f188-4782-a0de-03a75b843d60
  name: Materials by Type
  pageRef: /pages/materials-by-type
  weight: 60
- identifier: fc8329cf-cf38-41d0-a545-0de6673a9202
  name: Lecture Videos
  pageRef: /video_galleries/lecture-videos
  parent: ad94fe13-f188-4782-a0de-03a75b843d60
  weight: 10
- identifier: 24b31d1e-80df-47fa-aebe-835fdc6627ba
  name: Lecture Notes
  pageRef: /lists/lecture-notes
  parent: ad94fe13-f188-4782-a0de-03a75b843d60
  weight: 20
- identifier: a0c365db-8e06-4f85-9bfc-d5db19ebde73
  name: Lecture Code
  pageRef: /lists/lecture-code
  parent: ad94fe13-f188-4782-a0de-03a75b843d60
  weight: 30
- identifier: bbb42d1e-6482-44b7-af5b-40f124b0cd9a
  name: Finger Exercises
  pageRef: /pages/finger-exercises
  parent: ad94fe13-f188-4782-a0de-03a75b843d60
  weight: 40
- identifier: 9aeddd91-0da2-47fa-ab9a-c41eff6a71a6
  name: Problem Sets
  pageRef: /lists/problem-sets
  parent: ad94fe13-f188-4782-a0de-03a75b843d60
  weight: 50
- identifier: 1f1daa4b-4ed9-4bac-8371-db21d79dc87f
  name: Recitations
  pageRef: /lists/recitations
  parent: ad94fe13-f188-4782-a0de-03a75b843d60
  weight: 60
